FROM python:3.12-rc-alpine
RUN mkdir /app; adduser -D cdapi; ln -s /app/env/.env /app/.env
COPY downloadcd.py /app
COPY reqdbupdate.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
COPY .envdocker /app/env/.env
VOLUME /app/env
WORKDIR /app
USER cdapi
ENTRYPOINT [ "./downloadcd.py" ]
