version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    deploy:
      resources:
        limits: 
          memory: 5G
        reservations:
          memory: 500M
    ports:
      - "8180:8080"
    volumes:
      - type: volume
        source: jenkins
        target: /var/jenkins_home
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  jenkins: