version: "3.9"
services:
  jenkins:
    # image: jenkins:2.60.3
    image: steve353/jenkins:0.2
    container_name: jenkins
    deploy:
      resources:
        limits: 
          memory: 1G
        reservations:
          memory: 500M
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8180:8080"
    volumes:
      - type: volume
        source: jenkins
        target: /var/jenkins_home
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  jenkins: