apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins

---

apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins

---

# Use with minikube tunnel --bind-address=VMRealIP
apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins-ext
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: jenkins