pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
        '''
    }
  }
  stages {
    stage('Build Database') {
      steps {
        container('docker') {
          sh '''
            cd CDDBAPI/Database
            reg=`nslookup registry-int.docker-registry.svc.cluster.local | grep Address | tail -1 | awk '{print \$2}'`
            if ! docker build -t registry-int.docker-registry:5000/devdb:v\${BUILD_NUMBER} .
            then
              if ! docker build -t \${reg}:5000/devdb:v\${BUILD_NUMBER} .
              then
                echo "[FAILED]"
                exit 1
              fi
            fi
          '''
        }
      }
    }
    stage('Build API') {
      steps {
        container('docker') {
          sh '''
            cd CDDBAPI/Python
            reg=`nslookup registry-int.docker-registry.svc.cluster.local | grep Address | tail -1 | awk '{print \$2}'`
            if ! docker build -t registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER} .
            then
              if ! docker build -t \${reg}:5000/devapi:v\${BUILD_NUMBER} .
              then
                echo "[FAILED]"
                exit 1
              fi
            fi
          '''
        }
      }
    }
    stage('Build DB Updater') {
      steps {
        container('docker') {
          sh '''
            cd CDDBAPI/Python
            reg=`nslookup registry-int.docker-registry.svc.cluster.local | grep Address | tail -1 | awk '{print \$2}'`
            if ! docker build -f Dockerfile-dbupdate -t registry-int.docker-registry:5000/devdbupdater:v\${BUILD_NUMBER} .
            then
              if ! docker build -f Dockerfile-dbupdate -t \${reg}:5000/devdbupdater:v\${BUILD_NUMBER} .
              then
                echo "[FAILED]"
                exit 1
              fi
            fi
          '''
        }
      }
    }
    stage('Launch Test Environment') {
      steps{
        container('docker') {
          sh '''
            reg=`nslookup registry-int.docker-registry.svc.cluster.local | grep Address | tail -1 | awk '{print \$2}'`
            if ! docker run --rm -d --name devdb-v\${BUILD_NUMBER} registry-int.docker-registry:5000/devdb:v\${BUILD_NUMBER}
            then
              if ! docker run --rm -d --name devdb-v\${BUILD_NUMBER} \${reg}:5000/devdb:v\${BUILD_NUMBER}
              then
                exit 2
              fi
            fi

            mkdir denv
            echo "DBUSER=root
DBPASS=secret123
DBSRV=cddb:3306" >denv/.env

            if ! docker run --rm -d -v ./denv:/app/env --link devdb-v\${BUILD_NUMBER}:cddb registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER}
            then
              if ! docker run --rm -d -v ./denv:/app/env --link devdb-v\${BUILD_NUMBER}:cddb \${reg}:5000/devapi:v\${BUILD_NUMBER}
              then
                docker rm -f registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER}
                docker rm -f \${reg}:5000/devapi:v\${BUILD_NUMBER}
                exit 2
              fi
            fi
            if ! docker run --rm -d -v ./denv:/app/env --link devdb-v\${BUILD_NUMBER}:cddb registry-int.docker-registry:5000/devdbupdater:v\${BUILD_NUMBER}
            then
              if ! docker run --rm -d -v ./denv:/app/env --link devdb-v\${BUILD_NUMBER}:cddb \${reg}:5000/devdbupdater:v\${BUILD_NUMBER}
              then
                docker rm -f registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER}
                docker rm -f \${reg}:5000/devapi:v\${BUILD_NUMBER}
                docker rm -f registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER}
                docker rm -f \${reg}:5000/devapi:v\${BUILD_NUMBER}
              fi
            fi
          '''
        }
      }
    }
    stage('Run tests') {
      steps {
        container('docker') {
          sh '''
            echo "Doing some tests"
          '''
        }
      }
    }
    stage('Publish images') {
      steps {
        container('docker') {
          sh '''
            reg=`nslookup registry-int.docker-registry.svc.cluster.local | grep Address | tail -1 | awk '{print \$2}'`
            pushfail=0
            ippush=0
            if ! docker push registry-int.docker-registry:5000/devdb:v\${BUILD_NUMBER}
            then
              docker tag registry-int.docker-registry:5000/devdb:v\${BUILD_NUMBER} \${reg}:5000/devdb:v\${BUILD_NUMBER}
              if ! docker push \${reg}:5000/devdb:v\${BUILD_NUMBER}
              then
                pushfail=1
              else
                ippush=1
              fi
            fi
            if ! docker push registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER}
            then
              docker tag registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER} \${reg}:5000/devapi:v\${BUILD_NUMBER}
              if ! docker push \${reg}:5000/devapi:v\${BUILD_NUMBER}
              then
                pushfail=2
              fi
            fi
            if ! docker push registry-int.docker-registry:5000/devdbupdater:v\${BUILD_NUMBER}
            then
              docker tag registry-int.docker-registry:5000/devdbupdater:v\${BUILD_NUMBER} \${reg}:5000/devdbupdater:v\${BUILD_NUMBER}
              if ! docker push \${reg}:5000/devdbupdater:v\${BUILD_NUMBER}
              then
                pushfail=3
              fi
            fi

            echo "Clean up"
            docker rm -f registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER}
            docker rm -f \${reg}:5000/devapi:v\${BUILD_NUMBER}
            docker rm -f registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER}
            docker rm -f \${reg}:5000/devapi:v\${BUILD_NUMBER}
            docker rm -f registry-int.docker-registry:5000/devdbupdater:v\${BUILD_NUMBER}
            docker rm -f \${reg}:5000/devdbupdater:v\${BUILD_NUMBER}
            if [ "$ippush" -eq "0" ]
            then
              for imgs in registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER} registry-int.docker-registry:5000/devapi:v\${BUILD_NUMBER} registry-int.docker-registry:5000/devdbupdater:v\${BUILD_NUMBER}
              do
                docker rmi \$imgs
              done
            fi
            if [ "$ippush" -gt "0" ]
            then
              for imgs in \${reg}:5000/devapi:v\${BUILD_NUMBER} \${reg}:5000/devapi:v\${BUILD_NUMBER} \${reg}:5000/devdbupdater:v\${BUILD_NUMBER}
              do
                docker rmi \$imgs
              done
            fi
            echo "FAILED: \${pushfail}"
            exit \${pushfail}
          '''
        }
      }
    }
  }
}